name: dig_cli
description: A powerful command-line tool to automate building, cleaning, and packaging Flutter projects.
version: 1.2.1
homepage: https://github.com/Digvijaysinh2204/dig_cli

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  ansicolor: ^2.0.3
  args: ^2.7.0
  path: ^1.9.1
  yaml: ^3.1.3
  http: ^1.5.0
  pub_semver: ^2.2.0
  archive: ^4.0.7

dev_dependencies:
  lints: ^6.0.0

executables:
  dg: dig_cli